import { formatDayLong, formatMonthLong } from '@/lib/dates';
import type { BillSummary, Shop } from '@/types/models';
import type { Lang } from '@/theme/fonts';
import { urduFontCss } from './fontEmbed';

export type HtmlCtx = {
  lang: Lang;
  money: (v: number) => string;
  qty: (v: number) => string;
  num: (v: number, fractionDigits?: number) => string;
  shop: Shop | null;
};

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const L = {
  en: {
    bill: 'MILK BILL',
    for: 'Bill for',
    customer: 'Customer',
    area: 'Area',
    phone: 'Phone',
    description: 'Description',
    amount: 'Amount',
    milk: 'Milk',
    monthlyMilk: 'Monthly milk charge',
    perDay: 'per day',
    days: 'days',
    litres: 'L',
    otherItems: 'Other items',
    oldBalance: 'Old balance',
    paid: 'Paid this month',
    total: 'TOTAL TO PAY',
    nothing: 'Nothing to pay — thank you!',
    thanks: 'Thank you for your business.',
    dayByDay: 'Day-by-day milk',
    date: 'Date',
    qty: 'Qty',
    generated: 'Generated by MilkBook',
  },
  ur: {
    bill: 'دودھ کا بل',
    for: 'بل برائے',
    customer: 'گاہک',
    area: 'علاقہ',
    phone: 'فون',
    description: 'تفصیل',
    amount: 'رقم',
    milk: 'دودھ',
    monthlyMilk: 'ماہانہ دودھ کی رقم',
    perDay: 'روزانہ',
    days: 'دن',
    litres: 'لیٹر',
    otherItems: 'دیگر چیزیں',
    oldBalance: 'پرانا بقایا',
    paid: 'اس مہینے ادا کیا',
    total: 'کل واجب الادا',
    nothing: 'کچھ دینا باقی نہیں — شکریہ!',
    thanks: 'آپ کا بہت شکریہ۔',
    dayByDay: 'روزانہ کا دودھ',
    date: 'تاریخ',
    qty: 'مقدار',
    generated: 'ملک بک سے تیار شدہ',
  },
} as const;

/**
 * Standalone HTML for the printable / shareable bill.
 * Deliberately self-contained (inline CSS, embedded font) so expo-print can
 * render it with no network and the PDF looks identical on every device.
 */
export async function buildBillHtml(
  bill: BillSummary,
  ctx: HtmlCtx,
  opts: { includeBreakdown?: boolean } = {}
): Promise<string> {
  const ur = ctx.lang === 'ur';
  const s = L[ctx.lang];
  const fontCss = ur ? await urduFontCss() : '';

  const bodyFont = ur
    ? "'MB Nastaliq', 'Noto Nastaliq Urdu', 'Noto Naskh Arabic', serif"
    : "-apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";

  const rows: string[] = [];

  if (bill.customer.billingType === 'monthly') {
    rows.push(
      row(
        `${s.monthlyMilk}${bill.milkQty > 0 ? sub(`${ctx.qty(bill.milkQty)} ${s.litres} · ${ctx.num(bill.milkDays)} ${s.days}`) : ''}`,
        ctx.money(bill.fixedAmount)
      )
    );
  } else if (bill.milkQty > 0) {
    rows.push(
      row(
        `${s.milk}${sub(
          `${ctx.qty(bill.milkQty)} ${s.litres} × ${ctx.money(bill.customer.rate)} · ${ctx.num(
            bill.milkDays
          )} ${s.days} · ${ctx.qty(bill.avgQty)} ${s.litres} ${s.perDay}`
        )}`,
        ctx.money(bill.milkAmount)
      )
    );
  }

  bill.itemLines.forEach((l) => {
    rows.push(row(`${esc(l.name)}${sub(`× ${ctx.qty(l.qty)}`)}`, ctx.money(l.total)));
  });

  if (Math.abs(bill.previousBalance) >= 1) {
    rows.push(row(s.oldBalance, ctx.money(bill.previousBalance)));
  }
  if (bill.paidInMonth > 0) {
    rows.push(row(s.paid, `− ${ctx.money(bill.paidInMonth)}`, 'paid'));
  }

  const breakdown =
    opts.includeBreakdown && bill.deliveries.length > 0
      ? `
      <div class="section">
        <div class="section-title">${s.dayByDay}</div>
        <table class="grid">
          ${chunk(bill.deliveries.filter((d) => d.status === 'delivered'), 4)
            .map(
              (group) =>
                `<tr>${group
                  .map(
                    (d) =>
                      `<td><span class="d">${esc(formatDayLong(d.date, ctx.lang).replace(/ \d{4}$/, ''))}</span><b>${ctx.qty(
                        d.qty
                      )}</b></td>`
                  )
                  .join('')}${Array.from({ length: 4 - group.length })
                  .map(() => '<td class="empty"></td>')
                  .join('')}</tr>`
            )
            .join('')}
        </table>
      </div>`
      : '';

  return `<!DOCTYPE html>
<html lang="${ctx.lang}" dir="${ur ? 'rtl' : 'ltr'}">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>
  ${fontCss}
  * { box-sizing: border-box; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  body {
    margin: 0;
    padding: 26px 22px 30px;
    font-family: ${bodyFont};
    color: #0B1B3A;
    background: #fff;
    font-size: ${ur ? '15px' : '14px'};
    line-height: ${ur ? 2.05 : 1.5};
    direction: ${ur ? 'rtl' : 'ltr'};
  }
  .card { border: 1px solid #E2E9F5; border-radius: 18px; overflow: hidden; }
  .head {
    background: linear-gradient(135deg, #0E1B52 0%, #1B3FCB 62%, #2F72E8 100%);
    color: #fff; padding: 22px 22px 18px;
  }
  .shop { font-size: ${ur ? '25px' : '23px'}; font-weight: 700; margin: 0 0 2px; letter-spacing: -0.3px; }
  .shopmeta { font-size: 12.5px; opacity: 0.85; line-height: 1.6; }
  .billtag {
    display: inline-block; margin-top: 12px; padding: 5px 13px; border-radius: 999px;
    background: rgba(255,255,255,0.18); font-size: 12px; letter-spacing: 0.6px; font-weight: 700;
  }
  .who { padding: 18px 22px 4px; display: flex; justify-content: space-between; gap: 14px; }
  .who .name { font-size: ${ur ? '21px' : '19px'}; font-weight: 700; margin: 0; }
  .who .meta { font-size: 12.5px; color: #5A6B8C; }
  .who .month { text-align: ${ur ? 'left' : 'right'}; font-size: 12.5px; color: #5A6B8C; }
  table { width: 100%; border-collapse: collapse; }
  .lines { margin: 14px 0 0; }
  .lines td { padding: 11px 22px; border-top: 1px solid #EDF2FA; vertical-align: top; }
  .lines td.amt { text-align: ${ur ? 'left' : 'right'}; white-space: nowrap; font-weight: 600; font-variant-numeric: tabular-nums; }
  .lines td.amt.paid { color: #0E8F47; }
  .sub { display: block; font-size: 11.5px; color: #8C9BB8; font-weight: 400; line-height: 1.5; margin-top: ${ur ? '-6px' : '1px'}; }
  .total {
    display: flex; justify-content: space-between; align-items: center; gap: 12px;
    margin: 16px 14px; padding: 16px 18px; border-radius: 14px;
    background: #E7EDFF; border: 1px solid #C9D7EC;
  }
  .total .label { font-size: 13px; font-weight: 700; color: #12246B; letter-spacing: 0.4px; }
  .total .value { font-size: ${ur ? '26px' : '25px'}; font-weight: 800; color: #12246B; font-variant-numeric: tabular-nums; }
  .total.clear { background: #E1F6EA; border-color: #A9E3C3; }
  .total.clear .label, .total.clear .value { color: #0E8F47; }
  .section { margin: 6px 14px 0; padding: 14px 8px 4px; border-top: 1px dashed #DDE5F0; }
  .section-title { font-size: 12px; font-weight: 700; color: #5A6B8C; letter-spacing: 0.5px; margin-bottom: 8px; }
  .grid td { width: 25%; padding: 5px 6px; font-size: 11.5px; border: 1px solid #EDF2FA; text-align: center; }
  .grid td.empty { border-color: transparent; }
  .grid .d { display: block; color: #8C9BB8; font-size: 10.5px; }
  .foot { text-align: center; padding: 16px 22px 20px; color: #5A6B8C; font-size: 12px; }
  .foot .thanks { font-weight: 600; color: #0B1B3A; font-size: 13.5px; }
  .brand { margin-top: 8px; font-size: 10.5px; color: #A8B4CC; letter-spacing: 0.4px; }
</style>
</head>
<body>
  <div class="card">
    <div class="head">
      <p class="shop">${esc(ctx.shop?.name ?? (ur ? 'ملک بک' : 'MilkBook'))}</p>
      <div class="shopmeta">
        ${ctx.shop?.address ? `${esc(ctx.shop.address)}<br/>` : ''}
        ${ctx.shop?.phone ? `${s.phone}: ${esc(ctx.shop.phone)}` : ''}
      </div>
      <span class="billtag">${s.bill}</span>
    </div>

    <div class="who">
      <div>
        <p class="name">${esc(bill.customer.name)}</p>
        <div class="meta">
          ${bill.customer.route ? `${s.area}: ${esc(bill.customer.route)}<br/>` : ''}
          ${bill.customer.phone ? `${s.phone}: ${esc(bill.customer.phone)}` : ''}
        </div>
      </div>
      <div class="month">
        ${s.for}<br/><b style="color:#0B1B3A">${esc(formatMonthLong(bill.month, ctx.lang))}</b>
      </div>
    </div>

    <table class="lines">${rows.join('')}</table>

    <div class="total ${bill.total <= 0 ? 'clear' : ''}">
      <span class="label">${bill.total <= 0 ? s.nothing : s.total}</span>
      ${bill.total > 0 ? `<span class="value">${ctx.money(bill.total)}</span>` : ''}
    </div>

    ${breakdown}

    <div class="foot">
      <div class="thanks">${s.thanks}</div>
      <div class="brand">${s.generated}</div>
    </div>
  </div>
</body>
</html>`;
}

function row(label: string, amount: string, cls = ''): string {
  return `<tr><td>${label}</td><td class="amt ${cls}">${amount}</td></tr>`;
}

function sub(text: string): string {
  return `<span class="sub">${text}</span>`;
}

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}
